import { ruleTester } from "../../../tests/rule-tester.ts";
import rule from "./index.ts";

const options = [{ max: 4 }];
const error = (score: number) => ({ messageId: "tooComplex", data: { score, max: 4 } });

ruleTester.run("max-expression-complexity", rule, {
  valid: [
    ...[
      "f(g(), h(), j());",
      "const value = a + b * c;",
      "const label = enabled ? 'yes' : 'no';",
      "function label(enabled) { return enabled ? 'yes' : 'no'; }",
      "const value = config?.a?.b?.c ?? fallback;",
      "const data = { a: 1, nested: { values: [2, -3, 4n, -5n] } };",
      "source.first().second().third().fourth().done();",
      "source.first(g(), h()).second(j(), k()).third().done();",
      "source?.first().second?.().third().fourth().done();",
      "(source.first() as Source).second().third().fourth().done();",
      "source.first().second().third()`literal`;",
      "items.map(item => { const doubled = item.value * 2; return doubled + 1; });",
      "items.map(item => f(g(), h(), j()));",
      "items.map(function () { return f(g(), h(), j()); });",
      "f({ method() { return g(h(), j(), k()); } });",
      "let total = 0; for (const item of items) total += item.amount;",
      "value ??= f(g(), h(), j());",
      "const a = f(g()); const b = h(j()); const c = k(l());",
      "function f(value = a(b(), c(), d())) {}",
      "f(class { field = a(b(), c(), d()); method() { return g(h(), j(), k()); } });",
      "const { value = a(b(), c(), d()) } = source;",
      "const allowed = a() && b() && c();",
      "if (a() && b() && c()) {}",
      "const value = flag ? f(g()) : h(j());",
      "const value = !a() && !b();",
      "const value = await f(g(), h(), j());",
      "const value = transaction ? await transaction.get(query) : await query.get();",
      "const values = await Promise.all([loadA(), loadB(), loadC()]);",
      "if (Number.isNaN(index) || index < 1 || !key) {}",
      "User.create(FirstName.from(first), LastName.from(last), identity, team?.lang || Language.DEFAULT);",
      "f({ a: g(), b: h(), c: j(), d: k() });",
      "f([g(), h(), j(), k()]);",
      "const value = [a(), b(), c(), d(), e()];",
      "const value = { a: f(), b: g(), c: h(), d: j(), e: k() };",
      "function f() { const value = { a: g(), b: h(), c: j(), d: k(), e: l() }; }",
      "const schema = object({location: object({coords: object({x: number(), y: number()}), address: optional(object({id: optional(string())}))})});",
      "const label = 'Name: ' + first + ' ' + last + ' (' + role + ')';",
      "const label = `Name: ${first} ${last} (${role})`;",
      "const docs = 'one' + 'two' + 'three' + 'four' + 'five' + 'six';",
      "const s = ('prefix' as string) + value;",
    ].map((code) => ({ code, options })),
    { code: "f(g(), h(), j(), k());", options: [{ max: 5 }] },
    { code: "if (a && b && c && d && e) {}", options: [{ max: 1 }] },
    { code: "if ((a && b) && (c && d)) {}", options: [{ max: 1 }] },
    { code: "if (a || b || c || d || e) {}", options: [{ max: 1 }] },
    { code: "const x = -42; const y = -1n; const z = enabled ? a : b;", options: [{ max: 1 }] },
    { code: "const view = <div>{f()}{g()}{h()}{j()}{k()}</div>;", filename: "view.tsx", options },
    { code: "f(g(), h(), j());", filename: "input.js", options },
  ],
  invalid: [
    ...[
      "f(g(), h(), j(), k());",
      "f(g(h(j(k()))));",
      "new F(g(), h(), j(), k());",
      "tag`${a()}${b()}${c()}${d()}`;",
      "const value = a + b + c + d + e + f;",
      "total += f(g(), h(), j());",
      "target[f()] = g(h(), j(), k());",
      "function* values() { yield f(g(), h(), j()); }",
      "import(f(g(), h(), j()));",
      "const value = `${a()}${b()}${c()}${d()}${e()}`;",
      "const value = 'prefix' + a() + b() + c() + d() + e();",
      "const value = a() + b() + c() + 'suffix';",
      "const value = (a(), b(), c(), d(), e());",
      "const value = a() ?? b() ?? c() ?? d() ?? e();",
      "f(...g(), ...h(), ...j(), ...k());",
      "f(g(), h(), j(), k()) as Value;",
      "f(g(), h(), j(), k())!;",
      "f(g(), h(), j(), k()) satisfies Value;",
      "<Value>f(g(), h(), j(), k());",
      "f?.(g?.(), h(), j(), k());",
      "source.first().second(g(), h(), j(), k()).done();",
      "factory()()()()();",
      "function value() { return f(g(), h(), j(), k()); }",
      "throw f(g(), h(), j(), k());",
      "export default f(g(), h(), j(), k());",
      "export = f(g(), h(), j(), k());",
      "enum E { Value = f(g(), h(), j(), k()) }",
      "value ??= f(g(), h(), j(), k());",
      "if (f(g(), h(), j(), k())) {}",
      "while (f(g(), h(), j(), k())) { break; }",
      "do {} while (f(g(), h(), j(), k()));",
      "for (; f(g(), h(), j(), k());) { break; }",
      "for (f(g(), h(), j(), k());;) { break; }",
      "for (;;f(g(), h(), j(), k())) { break; }",
      "for (const item of f(g(), h(), j(), k())) {}",
      "for (const key in f(g(), h(), j(), k())) {}",
      "switch (f(g(), h(), j(), k())) {}",
      "switch (value) { case f(g(), h(), j(), k()): break; }",
      "function value(x = f(g(), h(), j(), k())) {}",
      "const { value = f(g(), h(), j(), k()) } = source;",
      "class C { field = f(g(), h(), j(), k()); }",
      "class C extends f(g(), h(), j(), k()) {}",
      "class C { [f(g(), h(), j(), k())]() {} }",
      "@f(g(), h(), j(), k()) class C {}",
      "const value = () => f(g(), h(), j(), k());",
      "if (a() && b() && c() && d()) {}",
      "const allowed = a() && b() && c() && d(); if (allowed) {}",
      "const value = [f(a(), b(), c(), d())];",
      "const value = {nested: {value: f(a(), b(), c(), d())}};",
      "const value = {...f(a(), b(), c(), d())};",
    ].map((code) => ({ code, options, errors: [error(5)], output: null })),
    ...["(a && b) || (c && d)", "a && (b || (c && d))"].map((expression) => ({
      code: `const result = ${expression};`,
      options: [{ max: 2 }],
      errors: [{ messageId: "tooComplex", data: { score: 3, max: 2 } }],
      output: null,
    })),
    ...[
      "obj[a() + b()](c(), d());",
      "const value = {[a()+b()]: f(c(),d())};",
      "const value = flag ? f(a(),b(),c(),d()) : fallback;",
    ].map((code) => ({ code, options, errors: [error(6)], output: null })),
    {
      code: "({ value = f(a(), b(), c(), d()) } = g(a(), b(), c(), d()));",
      options,
      errors: [error(10)],
      output: null,
    },
    {
      code: "const value = f(a(), b(), c(), d(), e());",
      options,
      errors: [{ ...error(6), line: 1, column: 14, endLine: 1, endColumn: 40 }],
      output: null,
    },
    ...[
      "f(g(), h(), j(), k()); a(b(), c(), d(), e());",
      "f(g(), h(), j(), k(), () => a(b(), c(), d(), e()));",
      "f(g(), h(), j(), k(), class { field = a(b(), c(), d(), e()); });",
      "const value = {one: f(a(),b(),c(),d()), two: g(a(),b(),c(),d())};",
    ].map((code) => ({ code, options, errors: [error(5), error(5)], output: null })),
    {
      code: "const view = <div>{f(a(),b(),c(),d())}</div>;",
      filename: "view.tsx",
      options,
      errors: [error(5)],
      output: null,
    },
    {
      code: "f(g(), h());",
      filename: "input.js",
      options: [{ max: 2 }],
      errors: [{ messageId: "tooComplex", data: { score: 3, max: 2 } }],
      output: null,
    },
  ],
});
