import { ruleTester } from "../../../tests/rule-tester.ts";
import rule from "./index.ts";

const options = [{ max: 2 }];

ruleTester.run("max-expression-depth", rule, {
  valid: [
    ...[
      "f(x);",
      "f(g(x));",
      "f(g(x), h(y), j(z));",
      "source.first().second().third().done();",
      "source.first(g(x)).second(h(x)).done();",
      "source?.first().second?.().done();",
      "const data = { nested: { values: [1, 2, 3] } };",
      "const label = enabled ? 'yes' : 'no';",
      "returnValue(enabled ? left : right);",
      "const value = enabled ? f(g(x)) : h(j(x));",
      "items.map(item => { const normalized = normalize(item); return encode(normalized); });",
      "items.map(item => f(g(item)));",
      "f(function () { return g(h(x)); });",
      "f({ method() { return g(h(x)); } });",
      "f(class { field = g(h(x)); method() { return g(h(x)); } });",
      "let total = 0; for (const item of items) total += item.amount;",
      "const parsed = parse(input); publish(encode(parsed));",
      "source.first().second()`literal`;",
      "f(g(x) as Value);",
    ].map((code) => ({ code, options })),
    { code: "f(g(h(x)));", options: [{ max: 3 }] },
    { code: "f(x);", options: [{ max: 1 }] },
    { code: "const view = <div>{f(g(x))}</div>;", filename: "view.tsx", options },
    { code: "f(g(x));", filename: "input.js", options },
  ],
  invalid: [
    ...[
      "new F(new G(new H(x)));",
      "f({ value: g(h(x)) });",
      "f([g(h(x))]);",
      "f(...g(h(x)));",
      "f(1 + g(h(x)));",
      "f(flag && g(h(x)));",
      "f(flag ? g(h(x)) : x);",
      "f(g(h(x)) as Value);",
      "f(g(h(x))!);",
      "f(g(h(x)) satisfies Value);",
      "f(<Value>g(h(x)));",
      "f(await g(h(x)));",
      "f(`prefix${g(h(x))}`);",
      "f((x, g(h(x))));",
      "f?.(g?.(h(x)));",
      "factory()()();",
      "tag`value${g(h(x))}`;",
      "import(g(h(x)));",
      "obj[g(h(x))]();",
      "(obj[g(h(x))])();",
      "source.first().second(g(h(x))).done();",
    ].map((code) => ({
      code,
      options,
      errors: [{ messageId: "tooDeep", data: { depth: 3, max: 2 } }],
      output: null,
    })),
    {
      code: "f(g(h(x)));",
      options,
      errors: [{ messageId: "tooDeep", line: 1, column: 0, endLine: 1, endColumn: 10 }],
      output: null,
    },
    {
      code: "f(g(h(j(x))));",
      options,
      errors: [{ messageId: "tooDeep", data: { depth: 4, max: 2 } }],
      output: null,
    },
    {
      code: "f(g(h(x))).next().done();",
      options,
      errors: [{ messageId: "tooDeep", column: 0, endColumn: 10 }],
      output: null,
    },
    {
      code: "items.map(item => f(g(h(item))));",
      options,
      errors: [{ messageId: "tooDeep", column: 18, endColumn: 31 }],
      output: null,
    },
    {
      code: "f(g(h(() => a(b(c(x))))));",
      options,
      errors: [
        { messageId: "tooDeep", data: { depth: 3, max: 2 } },
        { messageId: "tooDeep", data: { depth: 3, max: 2 } },
      ],
      output: null,
    },
    {
      code: "f(g(h(x))); a(b(c(y)));",
      options,
      errors: [{ messageId: "tooDeep" }, { messageId: "tooDeep" }],
      output: null,
    },
    {
      code: "const view = <div>{f(g(h(x)))}</div>;",
      filename: "view.tsx",
      options,
      errors: [{ messageId: "tooDeep" }],
      output: null,
    },
    {
      code: "f(g(x));",
      filename: "input.js",
      options: [{ max: 1 }],
      errors: [{ messageId: "tooDeep", data: { depth: 2, max: 1 } }],
      output: null,
    },
  ],
});
