import { ruleTester } from "../../../tests/rule-tester.ts";
import rule from "./index.ts";

ruleTester.run("prefer-domain-predicate naming boundaries", rule, {
  valid: [
    "const isX = a.amount > 10 && a.type === 'money';",
    "const expensiveMoney = a.amount > 10 && a.type === 'money'; if (expensiveMoney) use(a);",
    "let selected = a.amount > 10 && a.type === 'money';",
    "var selected = a.amount > 10 && a.type === 'money';",
    "selected = a.amount > 10 && a.type === 'money';",
    "state.selected = a.amount > 10 && a.type === 'money';",
    "const state = { selected: a.amount > 10 && a.type === 'money' };",
    "class State { selected = a.amount > 10 && a.type === 'money'; }",
    "const selected = !(a.amount > 10 && a.type === 'money');",
    "const selected = ((a.amount > 10 && a.type === 'money') as boolean);",
    "const selected = (a.amount > 10 && a.type === 'money') satisfies boolean;",
    "const selected = ['first', 'second'].includes(value);",
    "const selected = new Set(['first', 'second']).has(value);",
    "function f(a) { log(); const selected = a.amount > 10 && a.type === 'money'; return selected; }",
    "const allowed = ['first', 'second']; if (allowed.includes(value)) use();",
    "const allowed = new Set(['first', 'second']); if (allowed.has(value)) use();",
    "const allowed = ['first', 'second']; if (new Set(allowed).has(value)) use();",
    "import { allowed } from './categories'; if (allowed.includes(value)) use();",
    "function f(allowed) { if (allowed.includes(value)) use(); }",
    "if (policy.allowed.includes(value)) use();",
    "if (policy['allowed'].includes(value)) use();",
    "if (allowed.includes(node.type) || allowed.includes(node.type)) use();",
    "if (allowed.includes(first.type) && allowed.includes(second.type)) use();",
    "const canUse = allowed.includes(node.type) && node.state === 'ready';",
    "const canUse = allowed.includes(node.type) && privileged.includes(node.type);",
    "function f(value) { if (!allowed.includes(value)) throw new Error(); }",
  ],
  invalid: [
    ...[
      "if (a.amount > 10 && a.type === 'money') use(a);",
      "use(a.amount > 10 && a.type === 'money');",
      "const label = a.amount > 10 && a.type === 'money' ? 'yes' : 'no';",
      "const result = send(a.amount > 10 && a.type === 'money');",
      "const results = values.filter(a => a.amount > 10 && a.type === 'money');",
      "const results = [a.amount > 10 && a.type === 'money'];",
      "const { selected } = a.amount > 10 && a.type === 'money';",
      "state[key] = a.amount > 10 && a.type === 'money';",
      "selected ||= a.amount > 10 && a.type === 'money';",
      "const result = { [key]: a.amount > 10 && a.type === 'money' };",
      "const result = { selected: format(a.amount > 10 && a.type === 'money') };",
      "if (['first', 'second'].includes(value)) use();",
      "if (new Set(['first', 'second']).has(value)) use();",
      "const allowed = ['first', 'second']; if (allowed.includes(node.type) && node.state === 'ready') use();",
      "if (policy.allowed.includes(node.type) && node.state === 'ready') use();",
      "if (new Set(allowed).has(node.type) && node.state === 'ready') use();",
      "if (allowed.includes(node.type) && privileged.includes(node.type)) use();",
      "if (user.role === 'owner' || user.permissions.includes('manage')) edit();",
    ].map((code) => ({ code, errors: [{ messageId: "preferPredicate" }], output: null })),
    {
      code: "const view = <div>{a.amount > 10 && a.type === 'money' ? 'yes' : 'no'}</div>;",
      filename: "view.tsx",
      errors: [{ messageId: "preferPredicate" }],
      output: null,
    },
  ],
});
