import { ruleTester } from "../../../tests/rule-tester.ts";
import rule from "./index.ts";

const error = { messageId: "preferPredicate" };
ruleTester.run("prefer-domain-predicate", rule, {
  valid: [
    "const kinds = ['Array', 'Object']; if (kinds.includes(node.type)) use(node);",
    "const kinds = ['Array', 'Object'] as const; const alias = kinds; if (alias.includes(node.type)) use(node);",
    "const kinds = new Set(['Array', 'Object']); if (kinds.has(node.type)) use(node);",
    "const selected = ['Array', 'Object'].includes(node.type);",
    "if (node.isContainer()) use(node);",
    "if (isContainer(node)) use(node);",
    "if (node.type === 'Array') use(node);",
    "if (left.type === 'Array' || right.type === 'Object') use(left);",
    "if (node.type === 'Array' || node.parent.type === 'Object') use(node);",
    "if (node.type === 'Array' || node.type === 'Array') use(node);",
    "if (node.type === 'Array' || 'Array' == node.type) use(node);",
    "if (['Array', 'Array'].includes(node.type)) use(node);",
    "if (value != null && typeof value === 'object') inspect(value);",
    "if (value !== undefined && value !== null) inspect(value);",
    "if (value.enabled === true && value.ready === false) inspect(value);",
    "if (ready && permitted && connected) proceed();",
    "if (read().type === 'Array' || read().type === 'Object') use();",
    "if (node[first] === 'Array' || node[second] === 'Object') use();",
    "if (node.type === 'Array') one(); if (node.type === 'Object') two();",
    "const choice = flag ? node.type === 'Array' : node.type === 'Object';",
    "function isContainer(node) { return node.type === 'Array' || node.type === 'Object'; }",
    "function isContainer(node) { const kinds = ['Array', 'Object']; return kinds.includes(node.type); }",
    "function isContainer(node) { const kind = node.type; if (!kind) return false; return ['Array', 'Object'].includes(kind); }",
    "function isContainer(node) { const kind = node.type; if (!kind) { return false; } return ['Array', 'Object'].includes(kind); }",
    "function isContainer(node) { if (override) return true; return ['Array', 'Object'].includes(node.type); }",
    "function classification(node) { return !(['Array', 'Object'].includes(node.type)); }",
    "const isContainer = node => node.type === 'Array' || node.type === 'Object';",
    "const isContainer = function(node) { return ['Array', 'Object'].includes(node.type); };",
    "const isContainer = ((node) => ['Array', 'Object'].includes(node.type)) satisfies Predicate;",
    "const policy = { container(node) { return ['Array', 'Object'].includes(node.type); } };",
    "const policy = { ['container'](node) { return ['Array', 'Object'].includes(node.type); } };",
    "class Node { isContainer() { return ['Array', 'Object'].includes(this.type); } }",
    "class Node { get container() { return ['Array', 'Object'].includes(this.type); } }",
    "class Node { container = () => ['Array', 'Object'].includes(this.type); }",
    "policy.container = node => ['Array', 'Object'].includes(node.type);",
    "nodes.filter(function container(node) { return ['Array', 'Object'].includes(node.type); });",
    "const kinds = ['Array', 'Object']; function f(kinds) { if (kinds.includes(node.type)) use(); }",
    "const kinds = ['Array', 'Object']; { const kinds = ['Array']; if (kinds.includes(node.type)) use(); }",
    "let kinds = ['Array', 'Object']; if (kinds.includes(node.type)) use();",
    "const first = second; const second = first; if (first.includes(node.type)) use();",
    "function f(Set) { if (new Set(['Array', 'Object']).has(node.type)) use(); }",
    "const kinds = ['Array', ...other]; if (kinds.includes(node.type)) use();",
    "if (permissions.includes('manage')) edit();",
    "if (node['a.b'].type === 'Array' || node.a.b.type === 'Object') use();",
    "if (value >= 2 || 2 <= value) use();",
    "if ([0, -0, +0].includes(value)) use();",
    "if ([null, true].includes(value)) use();",
    "if ([, 'first', 'second'].includes(value)) use();",
    "if (['first', 'second'].includes(value, 1)) use();",
    "class C { #a; #b; method(value) { if (#a in value && #b in value) use(value); } }",
    "import { Set } from 'custom'; if (new Set(['first', 'second']).has(value)) use();",
  ],
  invalid: [
    ...[
      "if (node.type === 'Array' || node.type === 'Object') use(node);",
      "if (node.type !== 'Array' && node.type !== 'Object') use(node);",
      "if (node.type === 'Array' || 'Object' === node.type) use(node);",
      "if (response.status >= 200 && response.status < 300) use(response);",
      "if (200 <= response.status && 300 > response.status) use(response);",
      "if (user.role === 'owner' || user.permissions.includes('manage')) edit();",
      "if (user.role === 'owner' || user.permissions.has('manage')) edit();",
      "if (['Array', 'Object'].includes(node.type)) use(node);",
      "if (new Set(['Array', 'Object']).has(node.type)) use(node);",
      "if (['Array', 'Object']['includes'](node['type'])) use(node);",
      "if (node?.type === 'Array' || node?.type === 'Object') use(node);",
      "if ((node.type as string) === 'Array' || node.type! === 'Object') use(node);",
      "if ((['Array', 'Object'] as const).includes(node.type)) use(node);",
      "if (node.parent.type === 'Array' || node.parent.type === 'Object') use(node);",
      "if (node['type'] === 'Array' || node.type === 'Object') use(node);",
      "if (node['a.b'].type === 'Array' || node['a.b'].type === 'Object') use(node);",
      "if (value >= -5 && value <= +5) use(value);",
      "if (value >= -5n && value <= 5n) use(value);",
      "if (value === `first` || value === `second`) use(value);",
      "if (!(node.type === 'Array' || node.type === 'Object')) use(node);",
      "if (node.type === 'Array' || (node.type === 'Object' || node.type === 'Other')) use(node);",
      "if (['Array', 'Object'].includes(node.type) || node.type === 'Other') use(node);",
      "function process(node) { if (['Array', 'Object'].includes(node.type)) use(node); }",
      "function format(node) { return ['Array', 'Object'].includes(node.type) ? 'yes' : 'no'; }",
      "function process(node) { return send(['Array', 'Object'].includes(node.type)); }",
      "function isContainer(node) { log(); return ['Array', 'Object'].includes(node.type); }",
      "function isContainer(node) { if (!node) return undefined; return ['Array', 'Object'].includes(node.type); }",
      "function isContainer(node) { if (override) { log(); return false; } return ['Array', 'Object'].includes(node.type); }",
      "const policy = { [method](node) { return ['Array', 'Object'].includes(node.type); } };",
      "nodes.filter(node => ['Array', 'Object'].includes(node.type));",
    ].map((code) => ({ code, errors: [error], output: null })),
    {
      code: "if (node.type === 'A' || node.type === 'B') use();",
      errors: [
        {
          messageId: "preferPredicate",
          data: { subjects: "node" },
          line: 1,
          column: 4,
          endColumn: 42,
        },
      ],
      output: null,
    },
    {
      code: "if ((a.kind === 'x' || a.kind === 'y') && (b.kind === 'x' || b.kind === 'y')) use();",
      errors: [{ messageId: "preferPredicate", data: { subjects: "a, b" } }],
      output: null,
    },
    {
      code: "if (node.type === 'Array' || node.type === 'Object') use(); if (node.type === 'Other' || node.type === 'Last') use();",
      errors: [error, error],
      output: null,
    },
    {
      code: "const view = <div>{['Array', 'Object'].includes(node.type) ? 'yes' : 'no'}</div>;",
      filename: "view.tsx",
      errors: [error],
      output: null,
    },
  ],
});
