import { ruleTester } from "../../../tests/rule-tester.ts";
import rule from "./index.ts";

ruleTester.run("prefer-domain-predicate validation boundaries", rule, {
  valid: [
    "function check(value) { const invalid = value < 0 || value > 10; return; }",
    "function check(value) { if (!value) throw new Error(); return; const invalid = value < 0 || value > 10; }",
    "class Format { checkIntegrity() { if (!['png', 'jpeg'].includes(this.format)) throw new UnknownFormatError(this.format); } }",
    "const supported = ['png', 'jpeg']; class Format { check() { if (!supported.includes(this.format)) throw new UnknownFormatError(this.format); if (this.quality !== undefined && (this.quality < 0 || this.quality > 100)) throw new RangeError(); } }",
    "class Note { checkIntegrity(): void { if (typeof this.value !== 'number') throw new Error('number'); if (this.value < 0 || this.value > 10) throw ModelProblem.Invalid.reason(Note, 'range'); } }",
    "function arbitraryName(value) { if (value < 0 || value > 10) throw new Error('range'); }",
    "function arbitraryName(value) { if (value < 0 || value > 10) { throw new Error('range'); } return; }",
    "const check = value => { if (value < 0 || value > 10) throw new Error('range'); };",
    "checks.range = value => { if (value < 0 || value > 10) throw new Error('range'); };",
    "function check(value) { const minimum = limits.minimum + 1; if (value < minimum || value > 10) throw new Error('range'); }",
    "function check(value) { const invalid = value < 0 || value > 10; if (invalid) throw new Error('range'); }",
    "function check(value) { const allowed = ['first', 'second']; if (!allowed.includes(value)) throw new Error('invalid'); }",
    "function check(value) { if (value == null) return; if (value < 0 || value > 10) throw new Error('range'); }",
    "function check(value) { const bound = enabled ? 10 : 20; if (value < 0 || value > bound) throw new Error('range'); }",
    "function check(value) { if (value < 0 || value > 10) throw buildError(format(value)); }",
    "function check(value) { const label = `value: ${value}`; if (value < 0 || value > 10) throw new Error(label); }",
  ],
  invalid: [
    "function editDocument(doc) { if (doc.state === 'locked' || doc.state === 'archived') throw new AccessDenied(); performEdit(doc); }",
    "function checkIntegrity(value): void { work(); if (value < 0 || value > 10) throw new Error(); }",
    "function check(value) { if (value < 0 || value > 10) throw new Error(); this.value = value; }",
    "function check(value) { if (value < 0 || value > 10) throw new Error(); return value; }",
    "function check(value) { if (value < 0 || value > 10) throw new Error(); return undefined; }",
    "function check(value) { if (value < 0 || value > 10) { log(); throw new Error(); } }",
    "function check(value) { const result = performEdit(value); if (value < 0 || value > 10) throw new Error(); }",
    "function check(value) { const changed = state.value++; if (value < 0 || value > 10) throw new Error(); }",
    "function check(value) { const changed = state.value = value; if (value < 0 || value > 10) throw new Error(); }",
    "function check(value) { const changed = delete state.value; if (value < 0 || value > 10) throw new Error(); }",
    "function check(value) { const changed = [...produce()]; if (value < 0 || value > 10) throw new Error(); }",
    "async function check(value) { const changed = await work(); if (value < 0 || value > 10) throw new Error(); }",
    "function check(value) { if (value < 0 || value > 10) throw new Error(); else performEdit(value); }",
    "function check(value) { if ((value < 0 || value > 10) && work()) throw new Error(); }",
    "function check(value) { if (value < 0 || value > 10) return; }",
    "values.forEach(value => { if (value < 0 || value > 10) throw new Error(); });",
    "if (value < 0 || value > 10) throw new Error();",
    "function check(value) { const callbacks = [() => value < 0 || value > 10]; if (!value) throw new Error(); }",
    "function check(value) { if (!value) throw errorFor(value.kind === 'a' || value.kind === 'b'); }",
    "function check(value) { let local = 0; if (value < 0 || value > 10) throw new Error(); }",
    "function search(filters) { if (filters.kind === 'video' || filters.kind === 'any') searchVideos(); }",
    "posts.filter(post => post.audience.includes('public') || post.audience.includes('followers'));",
    "function visit(node) { if (['ArrayExpression', 'JSXElement'].includes(node.type)) processChildren(node); }",
    "function visit(node) { if (node.type === 'LogicalExpression' && node.operator !== '??') count(node); }",
  ].map((code) => ({ code, errors: [{ messageId: "preferPredicate" }], output: null })),
});
