import { ruleTester } from "../../../tests/rule-tester.ts";
import rule from "./index.ts";

const options = [{ max: 2 }];
ruleTester.run("max-decision-depth", rule, {
  valid: [
    ...[
      "const all = a && b && c && d && e;",
      "const alternatives = (a && b) || (c && d);",
      "const choice = a ? b : c;",
      "const choice = a ? b : c ? d : e;",
      "const choice = (a && b) ? c : d;",
      "const grouped = a && (b && (c || d));",
      "const negated = a && !(b && c);",
      "const data = {one: a && (b || c), two: d || (e && f)};",
      "outer(a && f(() => b || (c && d)));",
      "if (a) { if (b) { if (c) { work(); } } }",
      "const value = source?.value ?? fallback;",
      "f(g(h(j(k()))));",
    ].map((code) => ({ code, options })),
    { code: "a && ((b && c) && d);", options: [{ max: 1 }] },
    { code: "a || b || c || d;", options: [{ max: 1 }] },
    { code: "a && ((b && c) as boolean);", options: [{ max: 1 }] },
    { code: "const value = a && (b || (c && d));", options: [{ max: 3 }] },
    { code: "const view = <div>{a && (b || c)}</div>;", filename: "view.tsx", options },
    { code: "const value = (a && b) || (c && d);", filename: "input.js", options },
  ],
  invalid: [
    ...[
      "a && (b || (c && d));",
      "a || (b && (c || d));",
      "const value = a ? b : c ? d : e ? f : g;",
      "const value = a && (b ? c : d || e);",
      "const value = (a && (b || c)) ? d : e;",
      "const value = a && !(b || (c && d));",
      "const value = a && f(b || (c && d));",
      "const value = a && [b || (c && d)];",
      "const value = a && `${b || (c && d)}`;",
      "const value = a && (await f(b || (c && d)));",
      "const value = a && ((b || (c && d)) as boolean);",
      "const value = a && ((b || (c && d)) satisfies boolean);",
      "const value = a && (b || (c && d))!;",
      "const value = a && ((b || (c && d)) ?? fallback);",
      "const value = {nested: {value: a && (b || (c && d))}};",
      "const value = {[a && (b || (c && d))]: x};",
      "const value = {...f(a && (b || (c && d)))};",
      "class C { value = a && (b || (c && d)); }",
      "function f(value = a && (b || (c && d))) {}",
    ].map((code) => ({
      code,
      options,
      errors: [{ messageId: "tooDeep", data: { depth: 3, max: 2 } }],
      output: null,
    })),
    {
      code: "const result = a && (b || (c && d));",
      options,
      errors: [{ messageId: "tooDeep", line: 1, column: 15, endLine: 1, endColumn: 35 }],
      output: null,
    },
    {
      code: "a && (b || (c && (d || e)));",
      options,
      errors: [{ messageId: "tooDeep", data: { depth: 4, max: 2 } }],
      output: null,
    },
    {
      code: "a && f(() => b || (c && (d || e)));",
      options,
      errors: [{ messageId: "tooDeep", data: { depth: 3, max: 2 } }],
      output: null,
    },
    {
      code: "a && (b || (c && d)); e || (f && (g || h));",
      options,
      errors: [{ messageId: "tooDeep" }, { messageId: "tooDeep" }],
      output: null,
    },
    {
      code: "const fields = {one: a && (b || (c && d)), two: e || (f && (g || h))};",
      options,
      errors: [{ messageId: "tooDeep" }, { messageId: "tooDeep" }],
      output: null,
    },
    {
      code: "const view = <div>{a && (b || (c && d))}</div>;",
      filename: "view.tsx",
      options,
      errors: [{ messageId: "tooDeep" }],
      output: null,
    },
    {
      code: "a && (b || c);",
      filename: "input.js",
      options: [{ max: 1 }],
      errors: [{ messageId: "tooDeep", data: { depth: 2, max: 1 } }],
      output: null,
    },
  ],
});
